//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Solicitud
    {
        public int ID { get; set; }
        public int Sede { get; set; }
        public string ID_Empleado { get; set; }
        public string ID_Aprobado { get; set; }
        public int ID_Alma { get; set; }
        public decimal Cantidad { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha_Reg { get; set; }
        public int Estado { get; set; }
    
        public virtual Almacen Almacen { get; set; }
    }
}
