//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int ID { get; set; }
        public int Sede { get; set; }
        public int ID_Guia { get; set; }
        public int ID_Doc { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ID_Empleado { get; set; }
        public decimal Inafecta { get; set; }
        public decimal Total { get; set; }
        public byte[] Img { get; set; }
        public System.DateTime Fecha_Reg { get; set; }
        public int Estado { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Compra_Guia Compra_Guia { get; set; }
    }
}
