//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Guia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra_Guia()
        {
            this.Compra = new HashSet<Compra>();
        }
    
        public int ID { get; set; }
        public int Sede { get; set; }
        public string ID_Prov { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ID_Empleado { get; set; }
        public string ID_AProbado { get; set; }
        public byte[] Img { get; set; }
        public System.DateTime Fecha_Reg { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
