//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Cuerpo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra_Cuerpo()
        {
            this.Compra_Detalle = new HashSet<Compra_Detalle>();
        }
    
        public int ID { get; set; }
        public int ID_Moneda { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal Inafecta { get; set; }
        public decimal Igv { get; set; }
        public decimal Total { get; set; }
        public int Estado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Detalle> Compra_Detalle { get; set; }
    }
}
