//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Detalle
    {
        public int ID { get; set; }
        public int ID_Cuerpo { get; set; }
        public int ID_Alma { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Cant_Real { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public string Observ { get; set; }
        public int Estado { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Compra_Cuerpo Compra_Cuerpo { get; set; }
    }
}
