//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotiza_Detalle
    {
        public int ID { get; set; }
        public int ID_Producto { get; set; }
        public int ID_Cotiza { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public string Detalle { get; set; }
        public decimal Total { get; set; }
        public int Estado { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
