//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Cotiza_Detalle = new HashSet<Cotiza_Detalle>();
            this.Venta_Orden = new HashSet<Venta_Orden>();
        }
    
        public int ID { get; set; }
        public int ID_Sede { get; set; }
        public string RUC { get; set; }
        public string RazSocial { get; set; }
        public decimal Total { get; set; }
        public string ID_Empleado { get; set; }
        public string ID_Aprobado { get; set; }
        public int Estado { get; set; }
        public System.DateTime Fecha_Reg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotiza_Detalle> Cotiza_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Orden> Venta_Orden { get; set; }
    }
}
