//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string DNI { get; set; }
        public int ID_Cargo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public byte[] Clave { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public byte Sexo { get; set; }
        public byte[] Img { get; set; }
        public int Estado { get; set; }
        public System.DateTime Fecha_Reg { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
    
        public virtual Cargo Cargo { get; set; }
    }
}
