//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int ID { get; set; }
        public int ID_Tipo { get; set; }
        public int ID_doc { get; set; }
        public string ID_Prov { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal Inafecta { get; set; }
        public decimal Total { get; set; }
        public byte[] Img { get; set; }
        public int Estado { get; set; }
        public Nullable<System.DateTime> Fecha_reg { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Gasto_Tipo Gasto_Tipo { get; set; }
    }
}
