//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Cotiza_Detalle = new HashSet<Cotiza_Detalle>();
            this.Receta = new HashSet<Receta>();
            this.Venta_Detalle = new HashSet<Venta_Detalle>();
        }
    
        public int ID { get; set; }
        public int ID_Area { get; set; }
        public string Nombre { get; set; }
        public decimal Stock { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Cantidad_Min { get; set; }
        public string Unidad { get; set; }
        public decimal Precio { get; set; }
        public string Detalle { get; set; }
        public byte[] Img { get; set; }
        public int Estado { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotiza_Detalle> Cotiza_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Detalle> Venta_Detalle { get; set; }
    }
}
