//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ydRSoft.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_Cuerpo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta_Cuerpo()
        {
            this.Venta_Detalle = new HashSet<Venta_Detalle>();
        }
    
        public int ID { get; set; }
        public int ID_Moneda { get; set; }
        public decimal Cambio { get; set; }
        public decimal Inafecta { get; set; }
        public decimal Descuento { get; set; }
        public decimal Base { get; set; }
        public decimal IGV { get; set; }
        public decimal Total { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Detalle> Venta_Detalle { get; set; }
    }
}
